---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/home.md
  label: Home
- type: heading
  label: academic
- type: document
  path: content/contact.md
  label: Contact
  match: "**/*"
- type: document
  path: content/family.md
  label: family
  match: "**/*"
upload_dir: static/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
